### ISSUE TITLE
As a user I want to be able to search cards with commas in them

### ISSUE THREAD

**Issue by epiphanyplx** [ericjaychi/tigrex#28]
Love the program! 
I did notice that quotation marks allows me to search for now

**Comment by ericjaychi** [comment]
Hey @epiphanyplx. Thanks for creating an issue! I'll go ahead and see if I can patch this up for you, but for the time being it should be able to pick up the card if you don't do a comma for now or quotes as you said.

For example, `yuriko the tigers shadow` should work.

The program doesn't have to be super specific since it does a fuzzy search. So inputting something like `yuriko` will even be able to pick up the card.

**Comment by epiphanyplx** [comment]
Eric,

Thanks for the quick response! I love the project, struggled through
downloading/using Python/PIP just so that I could use it.
Good to know about just leaving comma out - I didn't realize I could just
write the first part of the card either.

Thanks again!
Andrew

**Comment by ericjaychi** [comment]
Hey Andrew,

I'm glad you enjoy it! I'll still go ahead and patch this issue up still. Thanks for bringing it to my attention.

Thanks!

**Comment by ericjaychi** [comment]
After taking a closer look into this issue, it seems like it is a bash issue and not so much a Python or application issue. If the user needs to be able to search with a comma or apostrophe, then the user will need to either escape the character or wrap the entire argument inside quotes.

Remember that the application uses fuzzy search, so entire names are not required. Scryfall's API will do its best to find a match with the given values, if the full value is needed, then please use quotes around the card name.
